# Generated by Django 4.0.2 on 2022-02-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('heroes_of_the_excerpt', models.TextField()),
                ('book', models.TextField(max_length=50)),
                ('book_author', models.TextField()),
            ],
        ),
    ]
